version: '3.4'

services:
  db:
    image: api-estudo-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: api_estudo
    ports:
      - 3308:3306
    networks:
      - erudio-network
      
  api-estudo:
    image: api-estudo
    build:
      context: .
      dockerfile: ApiEstudo/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 4430:8080
      - 44300:8081
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
